"""Subclass of Ui, which is generated by wxFormBuilder."""

import wx
import ui

# Implementing Ui
class PPServ( ui.Ui ):
    def __init__( self, parent ):
        ui.Ui.__init__( self, parent )
    
    # Handlers for Ui events.
    def start_all_service_click( self, event ):
        # TODO: Implement start_all_service_click
        pass
    
    def stop_all_service_click( self, event ):
        # TODO: Implement stop_all_service_click
        pass
    
    def edit_host_click( self, event ):
        # TODO: Implement edit_host_click
        pass
    
    def auto_run_click( self, event ):
        # TODO: Implement auto_run_click
        pass
    
    def advt_setting_click( self, event ):
        # TODO: Implement advt_setting_click
        pass
    
    def basic_setting_click( self, event ):
        # TODO: Implement basic_setting_click
        pass
    
    def open_cmd_click( self, event ):
        # TODO: Implement open_cmd_click
        pass
    
    
