#!/usr/bin/env python
# coding:utf-8

"""Subclass of Ui, which is generated by wxFormBuilder."""

import wx
import ui
import task_bar_icon

# Implementing Ui
class PPServ( ui.Ui ):
    def __init__( self, parent ):
        ui.Ui.__init__( self, parent )

        self.SetIcon(wx.Icon('icon.ico', wx.BITMAP_TYPE_ICO))
        self.tray_icon = task_bar_icon.TaskBarIcon(self)
        self.Bind(wx.EVT_CLOSE, self.OnHide)
        self.Bind(wx.EVT_ICONIZE, self.OnIconfiy)

        self.SetBackgroundColour('white')
        self.Center()
        self.Show()
    
    #窗口控制事件
    def OnHide(self, event):
        """隐藏"""
        self.Hide()

    def OnIconfiy(self, event):
        """点击关闭时只退出监控界面"""
        self.Hide()
        event.Skip()

    def OnClose(self, event):
        """退出"""
        self.tray_icon.Destroy()
        self.Destroy()

    # Handlers for Ui events.
    def start_all_service_click( self, event ):
        # TODO: Implement start_all_service_click
        pass
    
    def stop_all_service_click( self, event ):
        # TODO: Implement stop_all_service_click
        pass
    
    def edit_host_click( self, event ):
        # TODO: Implement edit_host_click
        pass
    
    def auto_run_click( self, event ):
        # TODO: Implement auto_run_click
        pass
    
    def advt_setting_click( self, event ):
        self.basic_panel.Hide()
        self.advt_panel.Show()
    
    def basic_setting_click( self, event ):
        self.basic_panel.Show()
        self.advt_panel.Hide()
    
    def open_cmd_click( self, event ):
        # TODO: Implement open_cmd_click
        pass
    
    
app = wx.App()
frame = PPServ(None)
app.MainLoop()